### ISSUE TITLE
getting: Error: Could not parse source map JSON in rollbar UI

### ISSUE THREAD

**Issue by jessesanford** [netguru/ember-cli-deploy-rollbar#4]
When I do a deploy after correctly configuring all my keys in my config/deploy.js I see the following in the rollbar dashboard:

{
  "message": "Error: Could not parse source map JSON", 
  "err": 1
}

The json that rollbar reports that was posted to the api from the ember-cli-deploy-rollbar command is:

{
  "access_token": "foobar", 
  "version": "fae3612", 
  "minified_url": "https://beta.foobar.com/assets/foo.js"
}

It seems that maybe you are missing other required fields? The following is from the rollbar api docs: https://rollbar.com/docs/source-maps/

```
Option B (Recommended): Upload pre-deploy

At the beginning of your deploy script (before the new code is in production), upload a source map package via our API.

Here's an example cURL command:

curl https://api.rollbar.com/api/1/sourcemap \
  -F access_token=aaaabbbbccccddddeeeeffff00001111 \
  -F version=version_string_here \
  -F minified_url=http://example.com/static/js/example.min.js \
  -F source_map=@static/js/example.min.map \
  -F static/js/site.js=@static/js/site.js \
  -F static/js/util.js=@static/js/util.js
Params

access_token
Your rollbar access token. Should be a post_server_item token (the same one that you use for sending deploy notifications).
version
A string identifying what version of your code this source map package is for. We recommend using the version number/string from your version control system, e.g. a full Git SHA.
Note that you will need to pass this same string in the on-page JS snippet, as documented above.
minified_url
The full URL of the minified file. Should start with http: or https:, which we'll strip off.
source_map
The contents of the source map, as a multipart file upload.
(each source file)
(Optional) Param name should be the path to the unminified JS file, as defined in the source map.
Value should be the contents of the source file, as a multipart file upload.
Response Codes

200 OK
Upload received successfully.
422 Unprocessable Entity
There was an error validating the upload. The error message should contain details of what went wrong.
```

**Comment by jniechcial** [comment]
Do you use gzipping in your deploy process? Can you show your build and deploy options (`deploy.js`, `ember-cli-build.js`)?

**Comment by jniechcial** [comment]
@therealjessesanford Any input on this one? :)

**Comment by adibsaad** [comment]
Is it possible that this is similar to this bug in ember-cli-deploy-sentry https://github.com/dschmidt/ember-cli-deploy-sentry/issues/8 ? The contents were gzipped and sentry couldn't handle gzipped sourcemaps.

**Comment by jniechcial** [comment]
@adibsaad It may be. I didn't get any input from @jessesanford. I am aware that Rollbar is not filling gzipped files - I communicated it in [Known Issues](https://github.com/netguru/ember-cli-deploy-rollbar#known-issues).

**Comment by jniechcial** [comment]
Closing due to lack of response.

**Comment by NullVoxPopuli** [comment]
any updates on this? I have this problem :-(

**Comment by jniechcial** [comment]
As I wrote before, I didn't get any additional input. If Rollbar is not accepting your sourcemaps during upload, you probably gzipped them before sending to Rollbar which is bad as Rollbar doesn't accept gzipped sourcemaps. If you are using `ember-cli-deploy-gzip` you can very easily opt out source maps from gzipping:
```[deploy.js]
// in your deploy.js
(...)
gzip: {
  filePattern: '**/*.{js,css,png,gif,ico,jpg,xml,txt,svg,swf,eot,ttf,woff,woff2}', // here I gzip basically everything except source maps
},
(...)
```

Give me a sign if it helps.

**Comment by NullVoxPopuli** [comment]
wooo!!

![image](https://cloud.githubusercontent.com/assets/199018/14921988/0fe4ccdc-0e03-11e6-924c-97e10c633f81.png)

**Comment by NullVoxPopuli** [comment]
I need a slash. lol

**Comment by jniechcial** [comment]
Nice that it worked out!
