### ISSUE TITLE
Environment not being set

### ISSUE THREAD

**Issue by Soliah** [netguru/ember-cli-deploy-rollbar#6]
I've got the following in my `deploy.js`:

```js
module.exports = function(deployTarget) {
  var ENV = {
    activateOnDeploy: true,

    rollbar: {
      accessToken: '...',
      accessServerToken: '...',
      minifiedPrependUrl: 'https://....cloudfront.net/...'
      environment: deployTarget
    }
  };

  ...
};
```

But the generated script config always has `environment: 'production'` set.

**Comment by Soliah** [comment]
Oops, its supposed to be nested under `rollbarConfig`.

**Comment by NullVoxPopuli** [comment]
rollbarconfig errors for me. I changed to rollbar, and it compiled. I don't have it reporting to rollbar though :-(

**Comment by NullVoxPopuli** [comment]
```javascript
   ENV.rollbar = {
      accessToken: 'client token' from rollbar,
      accessServerToken: 'server token from rollbar',
      minifiedPrependUrl: function(context){
        return [
          'https://s3.amazonaws.com/aeonvera-production/ember/assets/' + context.revisionData.revisionKey,
          'https://s3.amazonaws.com/aeonvera-production/ember/assets/'
        ];
      }
    };
```

this is what I have .. ember/assets/ is the folder where the js and maps are located, when an error occurs, rollbar isn't even attempted to be contacted :-(

**Comment by jniechcial** [comment]
Below you have my example:

```
ENV.rollbar = {
  accessToken: 'xxx',
  accessServerToken: xxx,
  minifiedPrependUrl: 'https://ember-deploy-test-kubanie.s3.eu-central-1.amazonaws.com/',
};
```
It works with current and former version of this addon.

How do you know if Rollbar is not even attempted to be contacted?

**Comment by NullVoxPopuli** [comment]
when I cause a js error, the console and network log don't show a post to rollbar :-(

this is my new config, btw:

in my deploy.js:
```
    rollbar: {
      accessToken: '...',
      accessServerToken: '...',
      minifiedPrependUrl: function(context){
        return ['https://s3.amazonaws.com/aeonvera-' + deployTarget + '/ember'];
      },
      environment: deployTarget,
      username: process.env.USER + '@' + process.env.HOSTNAME
    }
```

**Comment by NullVoxPopuli** [comment]
which outputs this:

```
var _rollbarConfig ={  
   "accessToken":"ca10480ec923459abdbe39a95c1181d9",
   "enabled":true,
   "captureUncaught":true,
   "environment":"production",
   "payload":{  
      "client":{  
         "javascript":{  
            "source_map_enabled":true,
            "code_version":"e3584261a76e9ef7cbb683b0e707f3d2",
            "guess_uncaught_frames":true
         }
      }
   }
};
```

I guess the keys aren't really important to hide, since they're rendered in the doc.

**Comment by jniechcial** [comment]
Ok so what is the issue? That the environment should not be `production`?

**Comment by NullVoxPopuli** [comment]
the issue 'was' both that my prependURL was incorrect, and that when I was testing, an error that caused ember-cli-rollbar to report an error didn't report the error for ember-cli-deploy-rollbar (but I found another place where ember-cli-deploy-rollbar works, so I could test that it was 'working' when an /uncaught/ error happened.

If you want to play around in my app, this is the screen that (when you click update/cancel) doesn't report to rollbar: https://aeonvera.com/user/edit

because I have an uncaught error on here: https://aeonvera.com/welcome/pricing (public, no need to login, just type something in the input box), it reports to rollbar.
